"""Registry completeness audit.

Random-pick discovery (Filip 2026-05-17): `post_Partners_id_documents` had
only `id` (path param) declared in `parameters`. POST endpoints obviously
need a body, but the registry was silent about it — the bot would have
called the API with an empty body and gotten 400/422.

This script audits all 655 non-internal user-facing tools in
`config/tool_data.json` and flags those where the registry metadata is
likely incomplete (cannot guarantee a successful API call).

Output: `docs/REGISTRY_AUDIT_{date}.md` — human-readable report.
Filip reviews, decides which tools to repair by hand from the source
Swagger (out of scope for the bot codebase).

Idempotent: re-running overwrites the report with current numbers.
"""
from __future__ import annotations

import json
import re
import sys
from collections import Counter, defaultdict
from datetime import date
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))
from services.v2.atomic_io import atomic_write_json  # noqa: E402
TOOL_DATA = REPO_ROOT / "config" / "tool_data.json"
DOCS_DIR = REPO_ROOT / "docs"

INTERNAL_HELPER_RE = re.compile(
    r"_(Distinct[A-Z][A-Za-z0-9]*|GroupBy|ProjectTo|metadata|"
    r"DeleteByCriteria|multipatch)$"
)

# Flag types
F_MISSING_BODY = "MISSING_BODY"           # POST/PUT/PATCH with 0 body params
F_LIKELY_MISSING_BODY = "LIKELY_MISSING_BODY"  # only path/query params
F_UNSAFE_REQUIRED = "UNSAFE_REQUIRED_TYPE"  # array/object required user_input
F_ROLE_RESTRICTED = "ROLE_RESTRICTED"     # personas_strict set


def is_internal(op_id: str) -> bool:
    return bool(INTERNAL_HELPER_RE.search(op_id))


def classify_tool(op_id: str, tool: dict) -> list:
    """Return list of flag strings for a tool. Empty list = clean."""
    flags: list = []
    method = (tool.get("method") or "GET").upper()
    params = tool.get("parameters") or {}

    user_input_params = {}
    for pname, pdef in params.items():
        if not isinstance(pdef, dict):
            continue
        dep = (pdef.get("dependency_source") or "user_input").lower()
        if dep != "user_input":
            continue
        user_input_params[pname] = pdef

    # Body schema completeness for mutating methods
    if method in {"POST", "PUT", "PATCH"}:
        body_params = [
            pname for pname, pdef in user_input_params.items()
            if (pdef.get("location") or "body").lower() == "body"
        ]
        non_body = [
            pname for pname, pdef in user_input_params.items()
            if (pdef.get("location") or "").lower() in {"path", "query", "header"}
        ]
        if not body_params and not non_body:
            flags.append(F_MISSING_BODY)
        elif not body_params and non_body:
            # All user_input is in path/query — body is empty
            flags.append(F_LIKELY_MISSING_BODY)

    # Unsafe required type (array/object the LLM can't structure)
    for pname, pdef in user_input_params.items():
        if not pdef.get("required"):
            continue
        ptype = (pdef.get("param_type") or "string").lower()
        if ptype in {"array", "object"}:
            flags.append(F_UNSAFE_REQUIRED)
            break  # one flag per tool, not per param

    # Role restriction (info only — bot bypasses with persona=None, but
    # backend may still enforce)
    personas = tool.get("personas_strict") or []
    if personas:
        flags.append(F_ROLE_RESTRICTED)

    return flags


def main():
    if not TOOL_DATA.exists():
        print(f"ERROR: {TOOL_DATA} not found", file=sys.stderr)
        sys.exit(1)

    data = json.loads(TOOL_DATA.read_text(encoding="utf-8"))
    tools = data.get("tools", {})

    audited: list = []
    for op_id, tool in tools.items():
        if is_internal(op_id):
            continue
        flags = classify_tool(op_id, tool)
        if flags:
            audited.append((op_id, tool, flags))

    # Stats
    total_non_internal = sum(1 for k in tools if not is_internal(k))
    flag_counter: Counter = Counter()
    by_method_flag: dict = defaultdict(lambda: Counter())
    for op_id, tool, flags in audited:
        method = (tool.get("method") or "GET").upper()
        for f in flags:
            flag_counter[f] += 1
            by_method_flag[method][f] += 1

    # Emit Markdown report
    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    today = date.today().isoformat()
    out_path = DOCS_DIR / f"REGISTRY_AUDIT_{today}.md"

    lines: list = []
    lines.append(f"# Registry audit — {today}")
    lines.append("")
    lines.append(
        f"Generated by `scripts/audit_registry_body_schemas.py` from "
        f"`config/tool_data.json` ({len(tools)} tools, "
        f"{total_non_internal} non-internal user-facing)."
    )
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append("| Flag | Count | % of non-internal |")
    lines.append("|---|---|---|")
    for flag in (
        F_MISSING_BODY, F_LIKELY_MISSING_BODY,
        F_UNSAFE_REQUIRED, F_ROLE_RESTRICTED,
    ):
        c = flag_counter.get(flag, 0)
        pct = (100 * c / total_non_internal) if total_non_internal else 0
        lines.append(f"| `{flag}` | {c} | {pct:.1f}% |")
    lines.append("")
    tools_with_any_flag = len(audited)
    pct_any = (100 * tools_with_any_flag / total_non_internal) if total_non_internal else 0
    lines.append(
        f"**{tools_with_any_flag} tools ({pct_any:.1f}%) have at least one flag.**"
    )
    lines.append("")

    lines.append("## By HTTP method")
    lines.append("")
    lines.append("| Method | MISSING_BODY | LIKELY_MISSING_BODY | UNSAFE_REQUIRED | ROLE_RESTRICTED |")
    lines.append("|---|---|---|---|---|")
    for method in ("POST", "PUT", "PATCH", "DELETE", "GET"):
        row = by_method_flag.get(method, Counter())
        lines.append(
            f"| {method} | {row.get(F_MISSING_BODY,0)} | {row.get(F_LIKELY_MISSING_BODY,0)} "
            f"| {row.get(F_UNSAFE_REQUIRED,0)} | {row.get(F_ROLE_RESTRICTED,0)} |"
        )
    lines.append("")

    lines.append("## Critical: MISSING_BODY (POST/PUT/PATCH s 0 declared params)")
    lines.append("")
    lines.append(
        "These tools have **no parameters declared at all** — the bot will "
        "send the request with empty body. API will likely 400/422."
    )
    lines.append("")
    lines.append("| Tool ID | Method | intent_summary |")
    lines.append("|---|---|---|")
    for op_id, tool, flags in audited:
        if F_MISSING_BODY in flags:
            method = (tool.get("method") or "GET").upper()
            intent = (tool.get("intent_summary") or "")[:80]
            lines.append(f"| `{op_id}` | {method} | {intent} |")
    lines.append("")

    lines.append("## High: LIKELY_MISSING_BODY (POST/PUT/PATCH s samo path/query params)")
    lines.append("")
    lines.append(
        "Mutating methods that have only path/query params declared — body "
        "schema is missing. Most REST conventions require body for these methods."
    )
    lines.append("")
    lines.append("| Tool ID | Method | intent_summary | Declared params |")
    lines.append("|---|---|---|---|")
    likely_count = 0
    for op_id, tool, flags in audited:
        if F_LIKELY_MISSING_BODY in flags:
            likely_count += 1
            if likely_count > 50:
                continue  # truncate after 50, show summary line
            method = (tool.get("method") or "GET").upper()
            intent = (tool.get("intent_summary") or "")[:60]
            param_names = list((tool.get("parameters") or {}).keys())[:6]
            lines.append(
                f"| `{op_id}` | {method} | {intent} | "
                f"{', '.join(param_names)} |"
            )
    if likely_count > 50:
        lines.append(f"| ... | | _(+{likely_count - 50} more, not shown)_ | |")
    lines.append("")

    lines.append("## Medium: UNSAFE_REQUIRED_TYPE")
    lines.append("")
    lines.append(
        "Tools requiring `array` or `object` user_input parameter. LLM "
        "extractor cannot reliably structure Croatian free-text into "
        "complex types. Param-asking flow will likely fail."
    )
    lines.append("")
    lines.append("| Tool ID | Method | Bad param |")
    lines.append("|---|---|---|")
    for op_id, tool, flags in audited:
        if F_UNSAFE_REQUIRED in flags:
            method = (tool.get("method") or "GET").upper()
            bad = []
            for pname, pdef in (tool.get("parameters") or {}).items():
                if isinstance(pdef, dict) and pdef.get("required"):
                    ptype = (pdef.get("param_type") or "").lower()
                    if ptype in {"array", "object"}:
                        bad.append(f"{pname}({ptype})")
            lines.append(f"| `{op_id}` | {method} | {', '.join(bad)} |")
    lines.append("")

    lines.append("## Info: ROLE_RESTRICTED (personas_strict set)")
    lines.append("")
    lines.append(
        "Tools that the registry restricts to specific personas. "
        "**Faza 1 removed bot-side persona filter**, so all users can NOW "
        "reach these tools — but the backend may still enforce role-based "
        "access (403 Forbidden). Use the LLM error translator (Faza 2) to "
        "surface a Croatian explanation instead of 'Tehnički problem'."
    )
    lines.append("")
    counts_by_persona: Counter = Counter()
    for op_id, tool, flags in audited:
        if F_ROLE_RESTRICTED in flags:
            for p in tool.get("personas_strict") or []:
                counts_by_persona[p] += 1
    for persona, cnt in counts_by_persona.most_common():
        lines.append(f"- `{persona}`: {cnt} tools")
    lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("## Next actions for Filip")
    lines.append("")
    lines.append(
        "1. **MISSING_BODY tools**: open Swagger source for each tool, "
        "copy body schema into `parameters` dict in tool registry "
        "(via `scripts/sync_tools.py` regeneration or manual edit)."
    )
    lines.append(
        "2. **LIKELY_MISSING_BODY**: same — most POST/PUT/PATCH need body "
        "fields declared so param-asking can ask user for them."
    )
    lines.append(
        "3. **UNSAFE_REQUIRED_TYPE**: either (a) provide structured input "
        "via a dedicated flow (like booking_flow), or (b) skip these "
        "tools from the bot until a structured-extraction extractor exists."
    )
    lines.append(
        "4. **ROLE_RESTRICTED**: no code action needed. Backend may 403; "
        "ApiErrorTranslator (Faza 2) will give user the right message."
    )

    out_path.write_text("\n".join(lines), encoding="utf-8")

    # Risky tools JSON — consumed by V2Engine to prefix a warn line on the
    # confirm message for tools whose registry metadata is incomplete.
    # Filip 2026-05-17 Faza 9.
    risky = {
        "missing_body": sorted(
            op_id for op_id, _, flags in audited if F_MISSING_BODY in flags
        ),
        "likely_missing_body": sorted(
            op_id for op_id, _, flags in audited if F_LIKELY_MISSING_BODY in flags
        ),
        "unsafe_required_type": sorted(
            op_id for op_id, _, flags in audited if F_UNSAFE_REQUIRED in flags
        ),
        "generated_at": today,
        "source": "scripts/audit_registry_body_schemas.py",
    }
    risky_path = REPO_ROOT / "config" / "risky_tools.json"
    # Atomic write — bot factory reads risky_tools.json at startup. Direct
    # write_text could leave a partial file if bot is loading concurrently.
    atomic_write_json(risky_path, risky)

    # Console summary
    print(f"Wrote {out_path}")
    print(f"Wrote {risky_path}")
    print(f"Total non-internal tools: {total_non_internal}")
    print(f"  MISSING_BODY:         {flag_counter.get(F_MISSING_BODY, 0)}")
    print(f"  LIKELY_MISSING_BODY:  {flag_counter.get(F_LIKELY_MISSING_BODY, 0)}")
    print(f"  UNSAFE_REQUIRED_TYPE: {flag_counter.get(F_UNSAFE_REQUIRED, 0)}")
    print(f"  ROLE_RESTRICTED:      {flag_counter.get(F_ROLE_RESTRICTED, 0)}")
    print(f"  Total flagged:        {len(audited)} ({pct_any:.1f}% of non-internal)")


if __name__ == "__main__":
    main()
