"""One-shot rebuild of config/tool_data.json from the archived legacy files.

After Phase 2 consolidation (2026-05-15) tool_data.json IS the source of
truth — edit it directly. This script exists only for emergency rebuild
from the frozen archives (kept ~1 month after Phase 4 rename):

Inputs (renamed to `.archive.json` during Phase 4):
  - config/processed_tool_registry.json          (Swagger truth — NOT archived,
                                                  regenerated by sync_tools.py)
  - config/tool_knowledge_base.archive.json      (legacy TKB content)
  - config/tool_anchor_enrichments.archive.json  (legacy anchor phrases)

Output:
  - config/tool_data.json  (overwrites)

The 5 dead TKB fields (`examples`, `returns`, `personas`, `mutation_safe`,
`requires_confirm`) are DROPPED — zero runtime readers, ~700 KB savings.

PURE REFACTOR — no LLM calls. Should only be run if tool_data.json gets
corrupted or you need to reset to the pre-Phase-2 baseline.

Run:
    python -X utf8 scripts/build_tool_data.py
"""
from __future__ import annotations

import json
import sys
import time
from collections import Counter
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

REPO = Path(__file__).resolve().parent.parent
REGISTRY = REPO / "config" / "processed_tool_registry.json"
# Phase 4 archived these — fall back to legacy name if archive doesn't exist
# (so this script keeps working both pre- and post-archive).
TKB = REPO / "config" / "tool_knowledge_base.archive.json"
if not TKB.exists():
    TKB = REPO / "config" / "tool_knowledge_base.json"
ANCHORS = REPO / "config" / "tool_anchor_enrichments.archive.json"
if not ANCHORS.exists():
    ANCHORS = REPO / "config" / "tool_anchor_enrichments.json"
OUT = REPO / "config" / "tool_data.json"


def main() -> None:
    print(f"Loading {REGISTRY.name} ...")
    registry = json.loads(REGISTRY.read_text(encoding="utf-8"))
    tools = registry.get("tools", [])
    print(f"  {len(tools)} tools")

    print(f"Loading {TKB.name} ...")
    tkb_root = json.loads(TKB.read_text(encoding="utf-8"))
    tkb_tools = tkb_root.get("tools", {})
    print(f"  {len(tkb_tools)} TKB entries")

    print(f"Loading {ANCHORS.name} ...")
    anchors = json.loads(ANCHORS.read_text(encoding="utf-8"))
    print(f"  {len(anchors)} anchor entries")

    # Merge per tool.
    merged: dict[str, dict] = {}
    quality_warnings: list[str] = []
    drop_stats = Counter()

    for tool in tools:
        op = tool.get("operation_id")
        if not op:
            quality_warnings.append("registry tool with empty operation_id (skipped)")
            continue

        tkb_entry = tkb_tools.get(op, {})
        anchor_phrases = anchors.get(op, [])

        if not tkb_entry:
            quality_warnings.append(f"{op}: no TKB entry")
        if not anchor_phrases:
            quality_warnings.append(f"{op}: no anchor phrases")

        # Drop the dead fields — they are not part of the new shape.
        for dead in ("examples", "returns", "personas", "mutation_safe",
                     "requires_confirm"):
            if dead in tkb_entry:
                drop_stats[dead] += 1

        merged[op] = {
            "operation_id": op,
            "method": tool.get("method") or tkb_entry.get("method") or "GET",
            "service": tool.get("service") or tool.get("service_name") or "",
            "path": tool.get("path", ""),
            "parameters": tool.get("parameters") or {},
            "required_params": tool.get("required_params") or [],
            "output_keys": tool.get("output_keys") or [],
            "is_mutation": tool.get("is_mutation", False),
            "tenant_scoped": tool.get("tenant_scoped", True),
            # Content fields (will be regen'd in Phase 3 with quality constraints)
            "intent_summary": (tkb_entry.get("intent_summary") or "").strip(),
            "use_when": tkb_entry.get("use_when") or [],
            "do_not_use_when": tkb_entry.get("do_not_use_when") or [],
            "anchors": list(anchor_phrases) if anchor_phrases else [],
        }

    out_doc = {
        "_meta": {
            "version": "1.0",
            "source_version": "phase1-union-merge",
            "merged_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            "source_files": {
                "registry": REGISTRY.name,
                "tkb": TKB.name,
                "anchors": ANCHORS.name,
            },
            "dropped_fields": dict(drop_stats),
            "tools_count": len(merged),
            "quality_warnings_count": len(quality_warnings),
        },
        "tools": merged,
    }

    # Atomic write
    OUT.write_text(json.dumps(out_doc, ensure_ascii=False, indent=2), encoding="utf-8")
    print()
    print(f"Wrote {OUT.relative_to(REPO)}")
    print(f"  tools: {len(merged)}")
    print(f"  dropped TKB fields:")
    for field, n in drop_stats.most_common():
        print(f"    {field:<22} {n} tools")
    if quality_warnings:
        print(f"  quality warnings ({len(quality_warnings)}):")
        for w in quality_warnings[:10]:
            print(f"    {w}")

    # Size delta report
    in_size = REGISTRY.stat().st_size + TKB.stat().st_size + ANCHORS.stat().st_size
    out_size = OUT.stat().st_size
    print()
    print(f"Combined input size:  {in_size:>10,} bytes ({in_size/1024/1024:.2f} MB)")
    print(f"tool_data.json size:  {out_size:>10,} bytes ({out_size/1024/1024:.2f} MB)")
    print(f"Delta vs combined:    {out_size - in_size:>10,} bytes")
    # The output is BIGGER than registry alone but smaller than the SUM of
    # the three inputs (because we drop the dead fields). The right
    # comparison is registry + intent_summary + use_when + do_not_use_when +
    # anchors — i.e. the content actually used at runtime.

    tkb_used_fields_size = 0
    for op, t in tkb_tools.items():
        for keep in ("intent_summary", "use_when", "do_not_use_when", "method"):
            v = t.get(keep)
            if v is not None:
                tkb_used_fields_size += len(json.dumps({keep: v}, ensure_ascii=False))
    print(f"  (TKB fields actually used at runtime: {tkb_used_fields_size:,} bytes)")
    print(f"  (TKB total: {TKB.stat().st_size:,} bytes — "
          f"{(TKB.stat().st_size - tkb_used_fields_size) / TKB.stat().st_size * 100:.0f}% was dead)")


if __name__ == "__main__":
    main()
