"""Export a CLEAN tool registry for the MobilityOne backend team (Filip 2026-05-26).

The two M1 request docs (docs/M1_ZAHTJEV_params / _filter) reference an attachment
`tool_registry.json` — "popis svih endpointa i njihovih parametara". Our internal
config/tool_data.json carries a lot of bot-internal noise (anchors, intent_summary,
use_when, personas, context_key, filter operators) that would only confuse the M1
team. This strips it to the endpoint + parameter surface they actually need:

    {operation_id, method, service, path, description, summary, tags,
     parameters: [{name, type, format, location, required, description, enum}]}

Tool-level `description`/`summary`/`tags` come from THEIR Swagger (sourced via
sync_tools.py → config/processed_tool_registry.json). They are NOT our internal
`intent_summary` (the generic-duplicate problem field), which is deliberately
excluded. Including their own Swagger descriptions in the attachment helps M1
team see where they have already written descriptions vs where they have gaps
(per Filip's 2026-05-28 ask).

Pure read of config/tool_data.json (params surface) + processed_tool_registry.json
(their Swagger metadata) → writes tool_registry.json at repo root.
Usage: python scripts/export_m1_registry.py [--out tool_registry.json]
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SRC = REPO / "config" / "tool_data.json"
# Their Swagger metadata source: processed_tool_registry.json is generated by
# sync_tools.py reading their live Swagger URL — so the `description`/`summary`/
# `tags` fields are verbatim what they themselves wrote in their Swagger.
PROCESSED = REPO / "config" / "processed_tool_registry.json"


def _clean_param(pdef: dict) -> dict:
    """Keep only the OpenAPI-relevant surface of one parameter."""
    out = {
        "name": pdef.get("name"),
        "type": pdef.get("param_type") or "string",
        "location": pdef.get("location"),
        "required": bool(pdef.get("required")),
    }
    if pdef.get("format"):
        out["format"] = pdef["format"]
    desc = (pdef.get("description") or "").strip()
    if desc:
        out["description"] = desc
    if pdef.get("enum_values"):
        out["enum"] = pdef["enum_values"]
    if (pdef.get("param_type") or "").lower() == "array" and pdef.get("items_type"):
        out["items_type"] = pdef["items_type"]
    return out


def _load_swagger_tool_meta() -> dict[str, dict]:
    """Build op_id -> {description, summary, tags} map from processed_tool_registry.
    These are THEIR Swagger fields (sync_tools.py pulled them from their live URL),
    NOT our internal intent_summary. Returns {} if file missing (graceful)."""
    if not PROCESSED.exists():
        return {}
    try:
        doc = json.loads(PROCESSED.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}
    out: dict[str, dict] = {}
    for t in doc.get("tools") or []:
        if not isinstance(t, dict):
            continue
        op_id = t.get("operation_id")
        if not op_id:
            continue
        meta: dict = {}
        for src_key in ("description", "summary"):
            v = (t.get(src_key) or "").strip()
            if v:
                meta[src_key] = v
        tags = t.get("tags") or []
        if isinstance(tags, list) and tags:
            meta["tags"] = [str(x) for x in tags if x]
        if meta:
            out[op_id] = meta
    return out


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=Path, default=REPO / "tool_registry.json")
    args = ap.parse_args()

    data = json.loads(SRC.read_text(encoding="utf-8"))
    tools_in = data.get("tools") or {}
    swagger_meta = _load_swagger_tool_meta()

    tools_out = []
    for op_id, e in tools_in.items():
        params = [
            _clean_param(pd)
            for pd in (e.get("parameters") or {}).values()
            if isinstance(pd, dict)
        ]
        out_op_id = e.get("operation_id") or op_id
        tool = {
            "operation_id": out_op_id,
            "method": e.get("method"),
            "service": e.get("service"),
            "path": e.get("path"),
        }
        # Their Swagger tool-level description/summary/tags (NEVER our intent_summary)
        meta = swagger_meta.get(out_op_id) or {}
        if meta.get("description"):
            tool["description"] = meta["description"]
        if meta.get("summary"):
            tool["summary"] = meta["summary"]
        if meta.get("tags"):
            tool["tags"] = meta["tags"]
        tool["parameters"] = params
        tools_out.append(tool)
    tools_out.sort(key=lambda t: (t.get("service") or "", t.get("path") or "", t.get("method") or ""))

    n_with_desc = sum(1 for t in tools_out if t.get("description"))
    n_with_summary = sum(1 for t in tools_out if t.get("summary"))
    payload = {
        "_meta": {
            "purpose": "MobilityOne endpoint + parameter surface for the backend team. "
                       "Reference for docs/M1_ZAHTJEV_params + _filter. "
                       "tool-level description/summary/tags = your Swagger; "
                       "bot-internal fields (intent_summary, anchors, personas) excluded.",
            "tool_count": len(tools_out),
            "tool_level_descriptions_present": n_with_desc,
            "tool_level_summaries_present": n_with_summary,
            "sources": ["config/tool_data.json", "config/processed_tool_registry.json"],
        },
        "tools": tools_out,
    }
    args.out.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8",
    )
    print(f"Wrote {args.out} — {len(tools_out)} tools, "
          f"{sum(len(t['parameters']) for t in tools_out)} params, "
          f"{n_with_desc} tool-level descriptions, {n_with_summary} summaries.")


if __name__ == "__main__":
    main()
